version: "3.8"

services:
  backend:
    build: .
    container_name: go-backend
    ports:
      - "8000:8000"
    environment:
      - DB_URL=host=db user=postgres password=postgres dbname=postgres sslmode=disable

    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
